pipeline {

    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/yourrepo/ai-devops-platform'
            }
        }

        stage('Build Docker') {
            steps {
                sh 'docker build -t ai-devops-app .'
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                sh 'kubectl apply -f kubernetes/deployment.yaml'
            }
        }

        stage('Verify') {
            steps {
                sh 'kubectl get pods'
            }
        }
    }
}